version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - misspell
    - noctx
    - staticcheck
    - unused
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
